version: '2'
volumes:
  esdata:
    driver: local
  graylogdata:
    driver: local
  mongodata:
    driver: local

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge

services:
  mongodb:
    image: mongo:3
    command: "mongod --config /conf/mongo.conf"
    volumes:
      - "mongodata:/data"
      - "./mongo:/conf/"
    networks:
      - internal

  elasticsearch:
    image: elasticsearch:2
    command: "elasticsearch -Des.cluster.name=graylog"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
      - "./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "./elasticsearch/logging.yml:/usr/share/elasticsearch/config/logging.yml:ro"
    environment:
      ES_MAX_MEM: 1g
    expose: 
      - 9200
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1536m
    networks:
      - internal

  graylog:
    image: graylog2/server:latest
    environment:
      GRAYLOG_PASSWORD_SECRET: Bgw7mYROifuwMCojIcuQ0PYCiuwtOWNSIQBV6fbIfNIzpFFxKrVcRDOxJOPBmjHPhOA5uT928Ll9LlfpPEWxsy9a4VSgZebo
      GRAYLOG_ROOT_PASSWORD_SHA2: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
      GRAYLOG_WEB_ENDPOINT_URI: http://glowbox:9000/api
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      GRAYLOG_MONGODB_URI: mongodb://mongodb/graylog
      GRAYLOG_MONGODB_MAX_CONNECTIONS: 100
      GRAYLOG_MONGODB_THREADS_ALLOWED_TO_BLOCK_MULTIPLIER: 5
      GRAYLOG_ELASTICSEARCH_CLUSTER_NAME: graylog
    volumes:
      - "graylogdata:/opt/graylog/data"
      - "./plugin/:/opt/graylog/plugin/"
    ports:
      - "9000:9000"
      - "5044:5044"
      - "1514:1514"
    expose:
      - 12201
    networks:
      - internal
      - external
    depends_on:
      - mongodb
      - elasticsearch

  logspout:
    image: vincit/logspout-gelf
    command: "gelf://graylog:12201"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - internal
    ports:
      - "8000:80"
    depends_on:
      - graylog