# Docker-compose for Graylog
version: '2'
volumes:
  esdata:
    driver: local
  graylogdata:
    driver: local
  mongodata:
    driver: local

networks:
  elasticnet:
    driver: bridge

services:
  mongodb:
    image: mongo:3
    command: "mongod --config /conf/mongo.conf"
    volumes:
      - "mongodata:/data"
      - "./mongo:/conf/"

  elasticsearch:
    image: elasticsearch:2
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    environment:
      cluster.name: "graylog"
      discovery.zen.ping.unicast.hosts: "[\"elasticsearch:9300\"]"
      path.repo: "[\"/usr/share/elasticsearch/data/\"]"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1536m

  graylog:
    image: graylog2/server:latest
    environment:
      GRAYLOG_PASSWORD_SECRET: Bgw7mYROifuwMCojIcuQ0PYCiuwtOWNSIQBV6fbIfNIzpFFxKrVcRDOxJOPBmjHPhOA5uT928Ll9LlfpPEWxsy9a4VSgZebo
      GRAYLOG_ROOT_PASSWORD_SHA2: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
      GRAYLOG_MONGODB_URI: mongodb://mongodb.service/graylog
      GRAYLOG_MONGODB_MAX_CONNECTIONS: 100
      GRAYLOG_MONGODB_THREADS_ALLOWED_TO_BLOCK_MULTIPLIER: 5
      GRAYLOG_ELASTICSEARCH_CLUSTER_NAME: graylog
    volumes:
      - "graylogdata:/opt/graylog/data"
      - "./plugin/:/opt/graylog/plugin/"
    links:
      - "elasticsearch:elasticsearch"
      - "mongodb:mongodb.service"
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"

  # Based on Logspout by Gliderlabs
  # https://github.com/gliderlabs/logspout
  #
  # I created a module to send Docker logs
  # from logspout to Graylog:
  # https://github.com/micahhausler/logspout-gelf
  # logspout:
  #   image: "micahhausler/logspout:gelf"
  #   hostname: logspout
  #   command: "gelf://graylog:12201"
  #   environment:
  #     LOGSPOUT: ignore
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   links:
  #     - "graylog:graylog"
  #   ports:
  #     - "8000:80"
